world save fix
CubicMC/cubic-server pull request #102
Opened 2023-01-18 07:28 UTC by Thomas-Harit

2023-01-18 13:31 UTC, huntears requested changes

2023-01-18 13:31 UTC, huntears commented on cubic-server/default/DefaultWorld.cpp
> +    std::vector<uint8_t> buffer = _data->serialize();
You need to destroy the nbt object after serializing it, else it will leak

2023-03-09 09:22 UTC, STMiki commented
This pr exists 🙃

2023-03-09 09:29 UTC, huntears commented
> This pr exists upside_down_face

Overall the PR is still fine in today's code, it can still be built upon I would say

2023-12-17 17:30 UTC, huntears commented
Currently working on it in #256

2023-12-17 17:30 UTC, closed without merging