Noisiest map (map generation)
CubicMC/cubic-server pull request #110
Opened 2023-02-12 18:19 UTC by STMiki

- [x] Fixed chunk serialization (biome too)
- [ ] Some noise map generation with the seed
- [ ] Maybe some tree ? don't know...

2023-02-13 08:17 UTC, huntears commented on CMakeLists.txt
> -set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++")
Why did you remove the static linking ?

2023-02-13 13:27 UTC, STMiki commented on CMakeLists.txt
> -set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++")
Oops 😅

2023-02-24 19:17 UTC, Trompettesib commented on cubic-server/Player.hpp
> +    std::unordered_map<Position2D, ChunkStateHolder> _chunks;
each player has a map of rendered or sended chunks
each dimension has a map of loading chunk

2023-02-24 21:06 UTC, Trompettesib requested changes

2023-02-25 00:21 UTC, Trompettesib reviewed
Things will change so I will review after

2023-02-25 00:28 UTC, Trompettesib approved these changes
👌 😅

2023-02-25 00:32 UTC, huntears approved these changes
augh

2023-02-25 00:32 UTC, merged