chat command handling
CubicMC/cubic-server pull request #113
Opened 2023-02-22 21:47 UTC by Trompettesib

2023-02-23 03:55 UTC, Trompettesib commented
I need to comment what I did btw

2023-02-23 23:56 UTC, STMiki reviewed
Why did you implement the permissions level system ? didn't we discuss that it will be reworked ? With like real permissions and stuff

2023-02-23 23:56 UTC, STMiki commented on cubic-server/command_parser/commands/QuestionMark.hpp
> +    QuestionMark() : CommandBase("?", "/help [<command>] (question mark)", 0) {}
/? instead of /help

2023-02-23 23:56 UTC, STMiki commented on cubic-server/protocol/ServerPackets.hpp
> +        ChatCommand = 0x04,
0x03, we are still in 1.19 (I think)
And yes, ChatMessage should be 0x04, but that does not fix the chat...

2023-03-03 19:02 UTC, huntears requested changes

2023-03-03 19:02 UTC, huntears commented on cubic-server/protocol/Structures.hpp
> +    struct argumentSignature
That should be in PascalCase

2023-03-03 20:45 UTC, huntears approved these changes

2023-03-03 20:51 UTC, STMiki approved these changes

2023-03-03 20:52 UTC, merged