Deop command
CubicMC/cubic-server pull request #114
Opened 2023-02-24 00:16 UTC by PierrickMarguin

Remove a player operator privileges

2023-03-15 14:26 UTC, Trompettesib approved these changes
looks good !

2023-03-28 12:25 UTC, STMiki reviewed
Same remark as the op command, see #112

2023-03-31 17:30 UTC, STMiki requested changes

2023-03-31 17:41 UTC, Trompettesib approved these changes

2023-03-31 17:42 UTC, STMiki approved these changes

2023-03-31 17:47 UTC, Trompettesib approved these changes

2023-03-31 17:47 UTC, STMiki approved these changes

2023-03-31 17:50 UTC, merged