Item code generation
CubicMC/cubic-server pull request #118
Opened 2023-03-08 17:43 UTC by Trompettesib

2023-03-08 22:14 UTC, huntears approved these changes

2023-03-09 07:57 UTC, STMiki requested changes
Reference for the win ! 💪

2023-03-09 07:57 UTC, STMiki commented on cubic-server/protocol_id_converter/itemConverter.cpp
> +    auto item = std::find_if(this->_items.begin(), this->_items.end(), [&id](Items::InternalItem i) {
```suggestion
    auto item = std::find_if(this->_items.begin(), this->_items.end(), [&id](const Items::InternalItem &i) {
```

2023-03-09 07:57 UTC, STMiki commented on cubic-server/protocol_id_converter/itemConverter.cpp
> +    auto item = std::find_if(this->_items.begin(), this->_items.end(), [&name](Items::InternalItem i) {
```suggestion
    auto item = std::find_if(this->_items.begin(), this->_items.end(), [&name](const Items::InternalItem &i) {
```

2023-03-09 07:57 UTC, STMiki commented on cubic-server/protocol_id_converter/itemConverter.cpp
> +Items::ItemId Items::ItemConverter::fromItemToProtocolId(std::string name) const {
```suggestion
Items::ItemId Items::ItemConverter::fromItemToProtocolId(const std::string &name) const {
```

2023-03-09 14:21 UTC, STMiki submitted a review, later dismissed
:ok_man:

2023-03-09 14:21 UTC, STMiki commented on cubic-server/types.hpp
>  typedef int32_t GlobalBlockId;
Honnestly, we could just remove the `Global`, will add that to #117

2023-03-09 14:22 UTC, huntears approved these changes

2023-03-09 14:46 UTC, huntears approved these changes

2023-03-09 14:47 UTC, STMiki requested changes
Missed theses :grinning:

2023-03-09 14:47 UTC, STMiki commented on cubic-server/protocol_id_converter/blockStates.cpp
> +BlockId Blocks::GlobalPalette::fromBlockToProtocolId(Blocks::Block block) const {
:upside_down_face: 
```suggestion
BlockId Blocks::GlobalPalette::fromBlockToProtocolId(const Blocks::Block &block) const {
```

2023-03-09 14:47 UTC, STMiki commented on cubic-server/protocol_id_converter/blockStates.hpp
> +            BlockId fromBlockToProtocolId(const Block block) const;
```cpp
            void initialize(const std::string &path = "blocks.json");
```

2023-03-09 14:58 UTC, STMiki approved these changes
:100:

2023-03-09 15:09 UTC, huntears approved these changes

2023-03-09 15:20 UTC, merged