Level loading
CubicMC/cubic-server pull request #124
Opened 2023-03-21 18:44 UTC by huntears

Loading the world should be pretty straight forward, but there's a lot to implement and to document.

2023-03-30 15:36 UTC, huntears commented
I hate the way I am mapping the parsed values tothe LevelData object, I really need to find another way instead of all those macros :(.

2023-04-10 20:04 UTC, huntears commented
> Loading the world should be pretty straight forward, but there's a lot to implement and to document.

It wasn't straight forward T_T

2023-04-10 20:07 UTC, Trompettesib commented
A basic gamemode command have been added in [this commit](https://github.com/CubicMC/cubic-server/pull/124/commits/4bb120358ce62abd985a29b0e2d7403f46e99128)

2023-05-26 02:38 UTC, huntears commented
Finally... I can rest now...

2023-05-26 12:34 UTC, STMiki requested changes

2023-05-26 12:34 UTC, STMiki commented on cubic-server/world_storage/Persistence.hpp
> +    std::vector<Position2D> regionStore; // TODO(huntears): Get proper getter/setter
todo

2023-05-26 12:34 UTC, STMiki commented on cubic-server/world_storage/Persistence.hpp
> +    void loadPlayerData(const Player *player, PlayerData *dest);
shared

2023-05-26 12:34 UTC, STMiki commented on cubic-server/world_storage/Persistence.hpp
> +    PlayerData loadPlayerData(const Player *player);
shared

2023-05-26 12:34 UTC, STMiki commented on cubic-server/world_storage/Persistence.cpp
> +            const uint64_t chunkOffset = header->locationTable[currentOffset].getOffset() * 0x1000;
Magic number

2023-05-29 01:08 UTC, Trompettesib submitted a review, later dismissed
it works on my computer, and I need the new thread pool so ... I guess I will approve

2023-05-29 01:10 UTC, Trompettesib commented
I do not like the fact that we depends on boost and that we need to have boost installed on the computer, but this will be changed soon

2023-05-29 01:43 UTC, Trompettesib approved these changes
I had to

2023-05-29 01:44 UTC, STMiki approved these changes

2023-05-29 01:44 UTC, STMiki commented on cubic-server/Dimension.cpp
> +        },
This is good for now because we are only managing the overworld, but when we start having players in another dimension, this will need to change

2023-05-29 01:44 UTC, Trompettesib commented on cubic-server/Client.hpp
> +#define __PCK_CALLBACK_PRIM(type, object) return object->_on##type(*(type *) packet.get())
I hope this will be fix one day

2023-05-29 01:44 UTC, STMiki commented on cubic-server/Client.hpp
> +#define __PCK_CALLBACK_PRIM(type, object) return object->_on##type(*(type *) packet.get())
OOF

2023-05-29 02:33 UTC, merged