General fixes
CubicMC/cubic-server pull request #137
Opened 2023-04-15 00:49 UTC by huntears

I don't really remember what I did, but overall some pointer stuff and other QOL.

Also fixed a bug with the command line :).

2023-04-15 01:16 UTC, Trompettesib commented on cubic-server/Permissions.cpp
> +                    if (player->getUsername() == name)
AUGH

2023-04-15 01:16 UTC, Trompettesib commented on cubic-server/Permissions.cpp
> +                        selectedPlayer.swap(player);
AUGH

2023-04-15 01:34 UTC, Trompettesib approved these changes
Insane

2023-04-15 01:34 UTC, Trompettesib commented on cubic-server/Server.cpp
> +const std::unordered_map<std::string_view, std::shared_ptr<WorldGroup>> &Server::getWorldGroups() const { return _worldGroups; }
no new line at end of file

2023-04-15 01:34 UTC, Trompettesib commented on cubic-server/interface/PlayersInterface.cpp
> +                    nb_players++;
AUGH

2023-04-15 01:34 UTC, Trompettesib commented on cubic-server/nbt.cpp
> +    return new Float(name, val.toReturn);
Finally <3

2023-04-15 12:14 UTC, STMiki commented on cubic-server/Dimension.cpp
> +            if (std::find_if(this->_loadingChunks[{x, z}].players.begin(), this->_loadingChunks[{x, z}].players.end(), [player](const std::shared_ptr<Player> current_player) {
Like written previously, this was a hack to see if the client was still connected, but now we can just get a hold of `weak_ptr` to player or client, try to get a `shared_ptr` from it, and send the chunk accordingly. And if it fails the client is no longer connected.
Pls fix ? :sweat_smile:
I can do it if you want, this is my shitty code anyway

2023-04-25 13:16 UTC, huntears commented on cubic-server/Client.cpp
> +    this->_player->_dim->removePlayer(_player->_id);
It could but I would prefer to let it this way, so that we can later let a player entity in the world without an actual player behind it.

2023-04-25 13:18 UTC, huntears commented on cubic-server/World.cpp
> +const WorldGroup *World::getWorldGroup() const { return _worldGroup; }
Uh, let me check.

2023-04-25 13:30 UTC, huntears commented on cubic-server/World.cpp
> +const WorldGroup *World::getWorldGroup() const { return _worldGroup; }
Fixed

2023-04-25 15:01 UTC, STMiki requested changes

2023-04-25 15:01 UTC, STMiki commented on cubic-server/Chat.cpp
Still a lot of raw ptr there

2023-04-25 16:12 UTC, Trompettesib requested changes
Looks good

2023-04-25 16:12 UTC, Trompettesib commented on cubic-server/protocol/PacketUtils.hpp
> +#include <optional>
```suggestion
```

2023-04-25 16:12 UTC, Trompettesib commented on cubic-server/protocol/serialization/popPrimaryType.hpp
> +#include "types.hpp"
```suggestion
```

2023-04-25 16:12 UTC, Trompettesib commented on cubic-server/world_storage/ChunkColumn.hpp
> +#include "nbt.hpp"
```suggestion
```

2023-04-26 11:09 UTC, huntears commented on cubic-server/command_parser/commands/CommandBase.hpp
> +#include <cstdint>
Doesn't compile without that :)

2023-04-26 11:48 UTC, STMiki approved these changes

2023-04-26 12:32 UTC, Trompettesib approved these changes
seems good (some things will be changed later)

2023-04-26 12:32 UTC, merged