Recipe system, does not handle item tags
CubicMC/cubic-server pull request #153
Opened 2023-05-08 04:48 UTC by PierrickMarguin

2023-05-14 12:36 UTC, huntears requested changes
Please document your code.

2023-05-14 14:40 UTC, Trompettesib reviewed
Looks good ! some minor things to change

2023-05-14 14:40 UTC, Trompettesib commented on cubic-server/recipes/CraftingShaped.cpp
> +        std::cout << " -> " << Server::getInstance()->getItemConverter().fromProtocolIdToItem(this->_result) << " (x" << this->_count << ')' << std::endl;
please use a string or a stringstream for all the std::cout
Same as Blasting.cpp

2023-05-14 14:40 UTC, Trompettesib commented on cubic-server/recipes/CraftingShapeless.cpp
> +        std::cout << "= \"" << Server::getInstance()->getItemConverter().fromProtocolIdToItem(this->_result) << "\" (x" << this->_count << ")" << std::endl;
Same as CraftingShaped.cpp

2023-05-14 14:40 UTC, Trompettesib commented on cubic-server/recipes/Recipes.cpp
> +        std::cout << "No data for this recipe." << std::endl;
Same as Blasting.cpp

2023-05-14 14:40 UTC, Trompettesib commented on cubic-server/recipes/Smelting.cpp
> +        std::cout << "\"" << Server::getInstance()->getItemConverter().fromProtocolIdToItem(this->_ingredient) << "\" -> \"" << Server::getInstance()->getItemConverter().fromProtocolIdToItem(this->_r
Same as Blasting.cpp

2023-05-14 14:40 UTC, Trompettesib commented on cubic-server/recipes/Smithing.cpp
> +        std::cout << "\"" << Server::getInstance()->getItemConverter().fromProtocolIdToItem(this->_base) << "\" + \"" << Server::getInstance()->getItemConverter().fromProtocolIdToItem(this->_addition
Same as Blasting.cpp

2023-05-14 14:40 UTC, Trompettesib commented on cubic-server/recipes/Smoking.cpp
> +        std::cout << "\"" << Server::getInstance()->getItemConverter().fromProtocolIdToItem(this->_ingredient) << "\" -> \"" << Server::getInstance()->getItemConverter().fromProtocolIdToItem(this->_r
Same as Blasting.cpp

2023-05-14 14:40 UTC, Trompettesib commented on cubic-server/recipes/StoneCutting.cpp
> +        std::cout << "\"" << Server::getInstance()->getItemConverter().fromProtocolIdToItem(this->_ingredient) << "\" -> \"" << Server::getInstance()->getItemConverter().fromProtocolIdToItem(this->_r
Same as Blasting.cpp

2023-05-16 16:39 UTC, Trompettesib submitted a review, later dismissed

2023-05-16 16:45 UTC, STMiki requested changes

2023-05-16 16:59 UTC, Trompettesib approved these changes

2023-05-16 17:11 UTC, STMiki approved these changes

2023-05-16 17:12 UTC, Trompettesib approved these changes

2023-05-16 17:26 UTC, merged