Adding AVX2 to significantly improve speed on arrays of Int32
CubicMC/cubic-server pull request #156
Opened 2023-05-09 20:29 UTC by HelifeWasTaken

2023-05-10 07:44 UTC, Matthieu-Sauer requested changes
I will check this evening if functionnality is working as expected.
You should create a "simd.hpp" or "intrinsics.hpp" which will decide (compile time) which intrinsics to use for a better extendability (we might want to target machines which do not have avx2 in the lobg run).

Also, I did not ask, however was this part of the code critical enough for intrinsics to be used? last time I benchmarked perlin noise generation and chunk accesses were the maik bottlenecks (did not check nbt as server crashes when I join on my machine)

2023-05-10 07:45 UTC, Matthieu-Sauer commented on cubic-server/nbt.cpp
> +    if (size >= 8) goto aligned8;
I would even suggest templated ones for same reason, easier to extend :)

2023-05-10 10:28 UTC, HelifeWasTaken commented on cubic-server/nbt.cpp
> +#ifdef __AVX2__
> I will check this evening if functionnality is working as expected. You should create a "simd.hpp" or "intrinsics.hpp" which will decide (compile time) which intrinsics to use for a better extendability (we might want to target machines which do not have avx2 in the lobg run).
> 
> Also, I did not ask, however was this part of the code critical enough for intrinsics to be used? last time I benchmarked perlin noise generation and chunk accesses were the maik bottlenecks (did not check nbt as server crashes when I join on my machine)

I actually tried to run the CubicMC server on the latest release (not the master tho) and found out that a lot of the time was used reading nbt list values so I guess -\_(' -')_/-

2023-05-11 19:19 UTC, huntears commented
@HelifeWasTaken If you can prove there is a significant performance gain I would be glad to merge this, but if there is not it just looks like more maintenability problems.

2023-05-18 13:34 UTC, HelifeWasTaken commented
> 
Might do it when I have time np

2023-08-02 21:25 UTC, huntears commented
Closing this PR as we are currently moving away from our homemade NBT library to a properly coded one.

2023-08-02 21:25 UTC, closed without merging