Special recipes handling to import every recipe and prevent exceptions
CubicMC/cubic-server pull request #159
Opened 2023-05-19 11:33 UTC by PierrickMarguin

2023-05-19 16:21 UTC, Trompettesib submitted a review, later dismissed

2023-05-21 22:47 UTC, STMiki requested changes
Good 👍 
Don't forget to use clang-format 😉

2023-05-22 13:52 UTC, Trompettesib approved these changes

2023-05-22 13:53 UTC, Trompettesib commented
I will do the last formatting things on my PR #152

2023-05-23 16:21 UTC, STMiki approved these changes

2023-05-23 16:21 UTC, merged