Registry
CubicMC/cubic-server pull request #177
Opened 2023-06-19 13:02 UTC by STMiki

Working registry created, and accessible from the `Server` class.

The nbt registry is only created once on startup and is reused when needed.

This mean that any change to the registry will throw / not work after initialization.

2023-06-23 01:21 UTC, Trompettesib approved these changes

2023-06-24 03:16 UTC, huntears requested changes
Making getters and setters constexpr will just increase compile time, please mark them inline.
The rest of the PR is good, it would have been good to use the new nbt librarie it is fine for now :).

2023-07-05 17:43 UTC, Trompettesib approved these changes

2023-07-06 08:11 UTC, huntears approved these changes

2023-07-07 15:32 UTC, Trompettesib approved these changes

2023-07-07 15:36 UTC, merged