Generic tree generation
CubicMC/cubic-server pull request #184
Opened 2023-07-19 15:22 UTC by NekoSelena

Fixing #181 & #182 with a generic tree generation for the Oak, Birch & Jungle trees

2023-07-20 00:15 UTC, Trompettesib submitted a review, later dismissed
C BÔ

*It's beautiful but in french and badly written*

2023-07-21 01:37 UTC, STMiki requested changes

2023-07-21 01:37 UTC, STMiki commented on cubic-server/world_storage/ChunkColumn.hpp
> +    const std::shared_ptr<Dimension> getDimension() const { return _dimension; }
```suggestion
    const std::shared_ptr<const Dimension> getDimension() const { return _dimension; }
```
`const std::shared_ptr<thing>` -> the pointer is const
`std::shared_ptr<const thing>` -> the object the pointer is pointing to is const

And shared_ptr has a const copy constructor from a non-const version, so this is the only thing you need to change

2023-07-21 07:39 UTC, huntears submitted a review, later dismissed
There's just the thing that Miki mentionned, but the rest if fine

2023-07-21 10:58 UTC, STMiki approved these changes

2023-07-21 11:07 UTC, huntears approved these changes

2023-07-21 11:09 UTC, merged