Respawn
CubicMC/cubic-server pull request #189
Opened 2023-07-21 13:23 UTC by Thomas-Harit

…th packets

2023-09-20 15:09 UTC, huntears requested changes
Quite a few things to change, I will be testing this PR tomorrow as I don't have the time to do it tonight.

2023-09-20 15:09 UTC, huntears commented on cubic-server/Player.cpp
> +    for (auto &player : this->_dim->getPlayers()) {
Please don't get a reference to the players, as that would not increase the reference count to the shared_ptr and the server might just crash if a player gets deleted while you're working on it.

2023-09-20 15:09 UTC, huntears commented on cubic-server/Player.cpp
> +        "You suck." // Message
Please use a better death message :)

2023-09-20 15:09 UTC, huntears commented on cubic-server/Player.cpp
> +        0, // Killer Entity id (0 for now because we don't know him)
Why do you not know him? I am pretty sure it is possible.

2023-09-20 15:09 UTC, huntears commented on cubic-server/Player.hpp
> +    void kill() override;
Please document that method.

2023-09-20 15:09 UTC, huntears commented on cubic-server/Player.hpp
> +    void sendRespawn(const protocol::Respawn &data);
Please document that method.

2023-09-20 15:09 UTC, huntears commented on cubic-server/Player.hpp
> +    void sendCombatDeath(const protocol::CombatDeath &packet);
Please document that method.

2023-09-20 15:09 UTC, huntears commented on cubic-server/Player.hpp
> +    // Respawn
That comment really is useless.

2023-09-20 15:09 UTC, huntears commented on cubic-server/entities/LivingEntity.cpp
> +        this->kill();
You could pass the entity_id of the killer here :)

2023-09-20 15:09 UTC, huntears commented on cubic-server/entities/LivingEntity.cpp
> + */
Please don't document in cpp files, only do it in hpp :)

2023-09-20 15:09 UTC, huntears commented on cubic-server/entities/LivingEntity.hpp
> +    virtual void kill();
Please document that method.

2023-09-20 15:09 UTC, huntears commented on cubic-server/protocol/ClientPackets.hpp
> +std::unique_ptr<std::vector<uint8_t>> createCombatDeath(const CombatDeath &);
Please document that function.

2023-09-20 15:09 UTC, huntears commented on cubic-server/protocol/ClientPackets.hpp
> +std::unique_ptr<std::vector<uint8_t>> createRespawn(const Respawn &in);
Please document that function.

2023-09-20 15:12 UTC, huntears commented
Also please watch your commits names because `Fixed Merge` and `Fixed clang-format` are not proper commit messages

2023-09-21 04:11 UTC, Trompettesib commented on cubic-server/Player.cpp
> +        "overworld", // World name
I'm not sure about that, cause you can respawn only in the overworld as we don't handle respawn anchors

2023-09-21 08:58 UTC, huntears requested changes
Almost there :)

2023-09-21 08:58 UTC, huntears commented on cubic-server/Player.cpp
> +        "a better death message :)" // Message
:))))))

2023-09-21 08:58 UTC, huntears commented on cubic-server/Player.hpp
> +    void kill(const int32_t &killerId) override;
Please document that method.

2023-09-21 08:58 UTC, huntears commented on cubic-server/default/Overworld.hpp
> +    std::string getDimensionName() const override { return "overworld"; }
Return const references here

2023-09-21 11:50 UTC, Trompettesib reviewed
Looks good but segfault :/

2023-11-14 17:10 UTC, huntears requested changes
Please don't invalidate other people's commit signatures if rebasing.
Only rebase when no conflicts are present, else do a merge then squash.
So please fix your commit history

2023-11-17 10:15 UTC, STMiki approved these changes, later dismissed

2023-11-17 10:15 UTC, STMiki commented on cubic-server/Dimension.hpp
> +    [[nodiscard]] virtual const std::string getDimensionTypeName() const = 0;
Use the `NODISCARD` define.
Will fix all of them later

2023-12-21 13:47 UTC, STMiki submitted a review, later dismissed

2023-12-22 23:18 UTC, STMiki approved these changes, later dismissed

2023-12-24 12:01 UTC, huntears requested changes
![image](https://github.com/CubicMC/cubic-server/assets/44233177/dbfcd811-c6b7-44e5-af7a-427419c584c1)

Dead players are not sent to newly connected players, therefore they don't show up in the tab menu.

Just disconnect after killing someone then reconnect and you will not see their name appear in the tab menu.

2024-01-06 18:57 UTC, Trompettesib submitted a review, later dismissed
Noice !

2024-01-12 14:48 UTC, huntears requested changes
Please resolve the conflict with master before review.

2024-02-22 11:26 UTC, closed without merging