Item durability handling
CubicMC/cubic-server pull request #223
Opened 2023-10-09 21:21 UTC by NekoSelena

- [ ] add durability handling of an item
- [ ] ensure that if an item reaches 0 durability, the next time it is used, it breaks and disappears

2023-11-28 03:01 UTC, STMiki requested changes

2023-11-28 03:01 UTC, STMiki commented on cubic-server/protocol/Structures.hpp
>      }
???

2023-11-28 03:01 UTC, STMiki commented on cubic-server/protocol/container/Container.cpp
> +}
???

2023-11-28 03:01 UTC, STMiki commented on cubic-server/protocol/container/Inventory.cpp
> +}
???

2023-11-28 11:12 UTC, NekoSelena commented on cubic-server/protocol/ServerPackets.hpp
> +    }
It was not me, I didn't do this

2023-11-28 11:12 UTC, NekoSelena commented on cubic-server/protocol/container/Container.cpp
> +}
Not my code, don't ask me

2023-11-28 11:12 UTC, NekoSelena commented on cubic-server/protocol/Structures.hpp
>      }
Not my code, don't ask me

2023-11-28 11:13 UTC, NekoSelena commented on cubic-server/protocol/container/Inventory.cpp
> +}
Not my code, don't ask me

2023-11-28 11:15 UTC, NekoSelena commented on cubic-server/items/UsableItem.hpp
> +        return ItemMaxDurabilityByType::Unbreakable;
It's just an `int`, not a `block ID`

2023-11-28 11:18 UTC, NekoSelena commented on cubic-server/protocol/ServerPackets.hpp
> +    }
You did, according to the git blame

2023-11-28 17:39 UTC, STMiki commented on cubic-server/items/UsableItem.hpp
> +        return ItemMaxDurabilityByType::Unbreakable;
Don't we have the same thing for item ?

2023-11-28 18:40 UTC, STMiki commented on cubic-server/items/UsableItem.hpp
> +        return ItemMaxDurabilityByType::Unbreakable;
The problem is, this is fine and all, but this may change between version, and it will be a pain to change file like this everyday

2023-11-28 19:19 UTC, STMiki approved these changes

2023-11-28 19:20 UTC, Trompettesib approved these changes
lgtm

2023-11-30 12:25 UTC, emneo-dev approved these changes

2023-11-30 13:47 UTC, merged