211 instant break blocks do not drop anything
CubicMC/cubic-server pull request #250
Opened 2023-11-21 18:49 UTC by Trompettesib

2023-11-25 23:12 UTC, huntears submitted a review, later dismissed

2023-11-26 14:15 UTC, STMiki requested changes

2023-11-26 14:15 UTC, STMiki commented on cubic-server/protocol_id_converter/blockDataConverter.cpp
> +        }();
No.

2023-11-26 14:15 UTC, STMiki commented on cubic-server/protocol_id_converter/blockDataConverter.cpp
> +        }();
```suggestion
        for (auto tool = block.value()["harvestTools"].rbegin(); tool != block.value()["harvestTools"].rend(); ++tool)
            b.harvestTool.push_back({stoi(tool.key()), tool.value()});
```

2023-11-26 16:55 UTC, huntears approved these changes

2023-11-26 17:28 UTC, STMiki approved these changes

2023-11-26 19:04 UTC, merged