Nether Update: Nether Wastes & Nether Portal
CubicMC/cubic-server pull request #261
Opened 2023-12-27 21:22 UTC by NekoSelena

2024-01-11 10:16 UTC, huntears requested changes
Most portals I tried to lit did not open up, and the only one that I got to open opened like this
![2024-01-11_11 05 28](https://github.com/CubicMC/cubic-server/assets/44233177/240c946d-3103-4581-a5cd-0301c8e00b96)

The biome in the nether is a plain above y 255, which looks really weird.

I also could not open a portal in the nether normally, it would open really weirdly and then wouldn't tp me except if I was on a specific block next to the portal.
![2024-01-11_11 13 57](https://github.com/CubicMC/cubic-server/assets/44233177/6ea82059-4cc1-47a3-8e91-4c213c1b553b)

2024-01-11 10:17 UTC, huntears commented
Also I don't know if it is related but calling stop crashes the server.
![image](https://github.com/CubicMC/cubic-server/assets/44233177/8698f2ca-1318-454f-b0c9-4ab0a40b4b92)

2024-01-13 18:43 UTC, STMiki submitted a review, later dismissed

2024-01-13 21:51 UTC, STMiki approved these changes

2024-01-13 23:52 UTC, huntears submitted a review, later dismissed

2024-01-14 01:41 UTC, STMiki commented on cubic-server/entities/Entity.cpp
> +        auto block = _dim->getBlock(pos);
then change the getBlock ?

2024-01-14 02:18 UTC, STMiki submitted a review, later dismissed

2024-01-14 02:40 UTC, huntears submitted a review, later dismissed

2024-01-14 02:41 UTC, huntears approved these changes

2024-01-14 02:41 UTC, Trompettesib approved these changes
love it !

2024-01-14 02:41 UTC, merged