Add furnace operation
CubicMC/cubic-server pull request #263
Opened 2023-12-28 18:29 UTC by Trompettesib

2024-01-09 20:07 UTC, PierrickMarguin approved these changes

2024-01-11 11:02 UTC, huntears requested changes
Some quirks to the function of the furnace but it will be ok.

2024-01-12 14:50 UTC, huntears approved these changes

2024-01-12 15:51 UTC, PierrickMarguin approved these changes
Noice

2024-01-12 16:25 UTC, merged