World basic gen
CubicMC/cubic-server pull request #55
Opened 2022-11-28 23:51 UTC by Trompettesib

2022-12-03 17:44 UTC, Trompettesib commented
I don't know if in this task I need to generate a ring of chunks around each players

2022-12-06 17:03 UTC, STMiki submitted a review, later dismissed

2022-12-20 11:43 UTC, huntears requested changes

2022-12-20 11:43 UTC, huntears commented on cubic-server/default/Overworld.cpp
> +#define NB_SPAWN_CHUNKS 19
Please use a constexpr variable for stuff like this.
It allows for proper typechecking.

2023-01-10 22:29 UTC, Trompettesib commented
Is it ok if I close this pr and delete the branch ?

2023-01-14 14:24 UTC, Trompettesib commented
This PR will be closed because another one (updated) has been made

2023-01-14 14:24 UTC, closed without merging