Update interface
CubicMC/cubic-server pull request #82
Opened 2023-01-12 22:27 UTC by NekoSelena

- [x] Add filter buttons
- [x] Replace label with TextView ( fix issue #68 )
- [ ] Make the filters work

2023-01-16 20:06 UTC, huntears requested changes
The log view scrolls down to the bottom all the time, it is impossible to check older logs than what is displayed on screen.

2023-01-17 04:18 UTC, Trompettesib approved these changes
Some things are cringe like the nessessity of using a new logLevel but overall it's good

2023-01-17 04:18 UTC, Trompettesib commented on cubic-server/interface/LogsInterface.cpp
> +  m_Reset("↺")
no sure about this character for reseting filters but I'm not a designer so I will not say anything ^^

2023-01-17 04:18 UTC, Trompettesib commented on cubic-server/interface/LogsInterface.hpp
> +        bool on_log_to_display();
function names aren't in pascalCase

2023-01-17 12:45 UTC, STMiki approved these changes

2023-01-17 15:26 UTC, huntears requested changes
View scrolls up and down continuously

2023-01-17 17:25 UTC, STMiki submitted a review, later dismissed

2023-01-17 17:32 UTC, Trompettesib approved these changes

2023-01-17 18:09 UTC, STMiki approved these changes

2023-01-17 18:10 UTC, huntears approved these changes

2023-01-17 18:10 UTC, merged