Stop command
CubicMC/cubic-server pull request #89
Opened 2023-01-15 12:19 UTC by Trompettesib

2023-01-15 15:07 UTC, STMiki requested changes

2023-01-15 20:32 UTC, huntears submitted a review, later dismissed

2023-01-15 21:34 UTC, STMiki submitted a review, later dismissed

2023-01-16 05:36 UTC, STMiki requested changes

2023-01-16 05:36 UTC, STMiki commented on cubic-server/Client.cpp
> +        _player->disconnect(reason);
add return

2023-01-16 15:42 UTC, STMiki approved these changes

2023-01-16 20:00 UTC, huntears approved these changes

2023-01-16 20:01 UTC, merged